/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki.CombatResult;
import static napakalaki.CombatResult.WinAndWinGame;
import napakalaki.Napakalaki;

/**
 *
 * @author Play
 */
public class NapakalakiView extends javax.swing.JFrame {

         private Napakalaki napakalakiModel;
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
    }
    
    public void setNapakalaki(Napakalaki n) {    
        
        napakalakiModel = n;    
        playerView1.setNapakalaki(napakalakiModel);
        this.napakalakiModel = playerView1.getNapakalaki();      
        playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
        // EXAMEN
        playerView1.setNapakalakiView(this);
        // FIN EXAMEN
        monsterView1.setMonster(napakalakiModel.getCurrentMonster()); 
        monsterView1.setVisible(false);
        Mensaje.setVisible(false);
        combatResult.setVisible(false);
        combatButton.setVisible(false);
        nextTurnButton.setVisible(false);
        // EXAMEN 
        panelExamen.setVisible(false);
        // FIN EXAMEN
    }
    // EXAMEN
    public void setVisiblePanelExamen(boolean b){
        panelExamen.setVisible(b);
    }
    // FIN DE EXAMEN

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combatResult = new javax.swing.JLabel();
        playerView1 = new GUI.PlayerView();
        Mensaje = new javax.swing.JLabel();
        nextTurnButton = new javax.swing.JButton();
        combatButton = new javax.swing.JButton();
        meetButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        monsterView1 = new GUI.MonsterView();
        panelExamen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combatResult.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        combatResult.setText("CombatResult");
        combatResult.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado del Combate"));
        getContentPane().add(combatResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 290, 50));
        getContentPane().add(playerView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Mensaje.setText("Mensaje");
        Mensaje.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aviso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 102, 102))); // NOI18N
        getContentPane().add(Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 290, 100));

        nextTurnButton.setText("Next Turn");
        nextTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextTurnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        combatButton.setText("Combat");
        combatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatButtonActionPerformed(evt);
            }
        });
        getContentPane().add(combatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

        meetButton.setText(" Meet the Monster");
        meetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(meetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 20, 10));
        getContentPane().add(monsterView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jLabel1.setText("Examen P4");
        panelExamen.add(jLabel1);

        jLabel2.setText("Salvador Anuar Olmedo Mohamed");
        panelExamen.add(jLabel2);

        getContentPane().add(panelExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 220, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetButtonActionPerformed
        monsterView1.setVisible(true);
        combatButton.setVisible(true);
        meetButton.setVisible(false);
        playerView1.EnableButtons(false);
    }//GEN-LAST:event_meetButtonActionPerformed

    private void combatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatButtonActionPerformed
        
        
        
        CombatResult combatResultado = napakalakiModel.developCombat();
        combatResult.setVisible(true);
        //Las etiquetas HTML, a parte de para dar color(no puedo ponerlo directamente en la etiqueta, porque si no, no es dinamico) tambien sirven para que el texto se ajuste
        //al marco que le hemos puesto, osea para que sea multilinea. Jlabel si no pones la etiqueta html, no es multilinea.
          switch (combatResultado) {
            case WinAndWinGame : 
              combatResult.setText("<html><div style='color: green;'>¡¡¡ H A S   G A N A D O   L A   P A R T I D A !!!</div></html>");
              break;
            case Win :
              combatResult.setText("<html><div style='color: green;'>Ganaste el combate</div></html>");
              break;
            case Lose :
              combatResult.setText("<html><div style='color: #008B8B;'>Has perdido el combate, te toca cumplir el mal rollo</div></html>");
              break;
            case LoseAndEscape :
              combatResult.setText("<html><div style='color: green;'>Perdiste el combate pero has logrado escapar</div></html>");
              break;
            case LoseAndDie :
              combatResult.setText("<html><div style='color: red;'>Perdiste el combate y además estás muerto</div></html>");
              break;
          }
               
        nextTurnButton.setVisible(true);
        combatButton.setVisible(false);
        playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_combatButtonActionPerformed

    private void nextTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTurnButtonActionPerformed
        // EXAMEN
        panelExamen.setVisible(false);
        // FIN EXAMEN
        
        if (!napakalakiModel.nextTurn()){
          Mensaje.setText("<html> ERROR <br> No cumples las condiciones para pasar de turno <br> O bien tienes más de 4 tesoros ocultos <br> O bien te queda mal rollo por cumplir<html>");
         Mensaje.setVisible(true);
        }else{
            Mensaje.setVisible(false);
            monsterView1.setVisible(false);
            combatResult.setVisible(false);
            meetButton.setVisible(true);
            combatButton.setVisible(false);
            nextTurnButton.setVisible(false);
            playerView1.EnableButtons(true);
            
            playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
            monsterView1.setMonster(napakalakiModel.getCurrentMonster());
            repaint();
            revalidate();
        }
        
        
    }//GEN-LAST:event_nextTurnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showView() {
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mensaje;
    private javax.swing.JButton combatButton;
    private javax.swing.JLabel combatResult;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton meetButton;
    private GUI.MonsterView monsterView1;
    private javax.swing.JButton nextTurnButton;
    private javax.swing.JPanel panelExamen;
    private GUI.PlayerView playerView1;
    // End of variables declaration//GEN-END:variables
}
