package GUI;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import napakalaki.Napakalaki;
import napakalaki.Player;
import napakalaki.Treasure;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Play
 */
public class PlayerView extends javax.swing.JPanel {
    private Napakalaki napakalakiModel;
    // EXAMEN
    private NapakalakiView napakalakiView;
    // FIN DE EXAMEN
    Player playerModel;
    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
    }
    
    public void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> aList) {
        // Se elimina la información antigua
        aPanel.removeAll();
        // Se recorre la lista de tesoros construyendo y añadiendo sus vistas
        // al panel
        for (Treasure t : aList) {
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTreasure (t);
            aTreasureView.setVisible (true);
            aPanel.add (aTreasureView);
        }
        // Se fuerza la actualización visual del panel
        aPanel.repaint();
        aPanel.revalidate();
    }

    public void setNapakalaki(Napakalaki n){
        this.napakalakiModel = n;
    }
    
    public Napakalaki getNapakalaki(){
        return napakalakiModel;
    }
    
    // EXAMEN
    public void setNapakalakiView(NapakalakiView n){
        this.napakalakiView = n;
    }
    // FIN DE EXAMEN   
    
    public void setPlayer (Player p) {
        
        playerModel = p;
        PlayerName.setText(playerModel.getName());
        PlayerLevel.setText("Nivel: " + Integer.toString(playerModel.getLevel()));
        fillTreasurePanel(hiddenTreasures, playerModel.getHiddenTreasures());
        fillTreasurePanel(visibleTreasures, playerModel.getVisibleTreasures());
        repaint();
        revalidate();
    }

    

    
    
    public ArrayList<Treasure> getSelectedTreasures(JPanel aPanel) {
        // Se recorren los tesoros que contiene el panel,
        // almacenando en un vector aquellos que están seleccionados.
        // Finalmente se devuelve dicho vector.
        TreasureView tv;
        ArrayList<Treasure> output = new ArrayList();
        for (Component c : aPanel.getComponents()) {
            tv = (TreasureView) c;
            if (tv.isSelected()) {
                output.add(tv.getTreasure());
            }
        }
        return output;
    }
    
    public void EnableButtons(boolean b){
        BuyButton.setEnabled(b);
        //DiscardTreasureButton.setEnabled(b);
        MakeVisibleButton.setEnabled(b);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayerName = new javax.swing.JLabel();
        PlayerLevel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        BuyButton = new javax.swing.JButton();
        MakeVisibleButton = new javax.swing.JButton();
        DiscardTreasureButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        hiddenTreasures = new javax.swing.JPanel();
        visibleTreasuresScroll = new javax.swing.JScrollPane();
        visibleTreasures = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlayerName.setText("Nombre");
        add(PlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        PlayerLevel.setText("Nivel");
        add(PlayerLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));
        add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 10, 20));

        BuyButton.setText("BuyLevels");
        BuyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyButtonActionPerformed(evt);
            }
        });
        add(BuyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        MakeVisibleButton.setText("Make Visible");
        MakeVisibleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeVisibleButtonActionPerformed(evt);
            }
        });
        add(MakeVisibleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        DiscardTreasureButton.setText("Discard Treasures");
        DiscardTreasureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscardTreasureButtonActionPerformed(evt);
            }
        });
        add(DiscardTreasureButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 160, -1));
        add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, 10));

        hiddenTreasures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        add(hiddenTreasures, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 400, 110));

        visibleTreasuresScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        visibleTreasuresScroll.setAutoscrolls(true);
        visibleTreasuresScroll.setMinimumSize(new java.awt.Dimension(12, 12));
        visibleTreasuresScroll.setPreferredSize(new java.awt.Dimension(12, 12));

        visibleTreasures.setMinimumSize(new java.awt.Dimension(12, 12));
        visibleTreasures.setPreferredSize(new java.awt.Dimension(12, 12));
        visibleTreasuresScroll.setViewportView(visibleTreasures);

        add(visibleTreasuresScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 400, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void MakeVisibleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeVisibleButtonActionPerformed
       // TODO add your handling code here:
        ArrayList<Treasure> selHidden = getSelectedTreasures(hiddenTreasures);
        napakalakiModel.makeTreasuresVisibles(selHidden);
        setPlayer(napakalakiModel.getCurrentPlayer());
        
    }//GEN-LAST:event_MakeVisibleButtonActionPerformed

    private void DiscardTreasureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscardTreasureButtonActionPerformed
        
        ArrayList<Treasure> selHidden = getSelectedTreasures(hiddenTreasures);
        napakalakiModel.discardHiddenTreasures(selHidden);
        ArrayList<Treasure> selVisible = getSelectedTreasures(visibleTreasures);
        napakalakiModel.discardVisibleTreasures(selVisible);
        setPlayer(napakalakiModel.getCurrentPlayer());
        
    }//GEN-LAST:event_DiscardTreasureButtonActionPerformed

    private void BuyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyButtonActionPerformed
           
        ArrayList<Treasure> selHidden = getSelectedTreasures(hiddenTreasures);
        ArrayList<Treasure> selVisible = getSelectedTreasures(visibleTreasures);           
        napakalakiModel.getCurrentPlayer().buyLevels(selVisible, selHidden);
        // EXAMEN
        napakalakiView.setVisiblePanelExamen(true);
        // FIN EXAMEN
        setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_BuyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuyButton;
    private javax.swing.JButton DiscardTreasureButton;
    private javax.swing.JButton MakeVisibleButton;
    private javax.swing.JLabel PlayerLevel;
    private javax.swing.JLabel PlayerName;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel hiddenTreasures;
    private javax.swing.JPanel visibleTreasures;
    private javax.swing.JScrollPane visibleTreasuresScroll;
    // End of variables declaration//GEN-END:variables
}
