/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import napakalaki.CombatResult;
import static napakalaki.CombatResult.WinAndWinGame;
import napakalaki.Napakalaki;

/**
 *
 * @author Play
 */
public class NapakalakiView extends javax.swing.JFrame {

         private Napakalaki napakalakiModel;
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
    }
    
    public void setNapakalaki(Napakalaki n) {    
        
        napakalakiModel = n;    
        playerView1.setNapakalaki(napakalakiModel);
        this.napakalakiModel = playerView1.getNapakalaki();      
        playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
        monsterView1.setMonster(null);
        monsterView1.setVisible(true);
        //Mensaje.setVisible(false);
        combatResult.setVisible(false);
        combatButton.setVisible(false);
        nextTurnButton.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combatResult = new javax.swing.JLabel();
        playerView1 = new GUI.PlayerView();
        nextTurnButton = new javax.swing.JButton();
        combatButton = new javax.swing.JButton();
        meetButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        monsterView1 = new GUI.MonsterView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 500));
        setPreferredSize(new java.awt.Dimension(857, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combatResult.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        combatResult.setText("CombatResult");
        combatResult.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado del Combate"));
        getContentPane().add(combatResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 290, 50));
        getContentPane().add(playerView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        nextTurnButton.setText("Next Turn");
        nextTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextTurnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 90, -1));

        combatButton.setText("Combat");
        combatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatButtonActionPerformed(evt);
            }
        });
        getContentPane().add(combatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, -1, -1));

        meetButton.setText(" Meet the Monster");
        meetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(meetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 20, 10));
        getContentPane().add(monsterView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 320, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetButtonActionPerformed
        //monsterView1.setVisible(true);
        monsterView1.setMonster(napakalakiModel.getCurrentMonster());
        combatButton.setVisible(true);
        combatButton.setEnabled(true);
        meetButton.setVisible(false);
        playerView1.enableBuy(false);
        playerView1.enableMake(false);
    }//GEN-LAST:event_meetButtonActionPerformed

    private void combatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatButtonActionPerformed
        CombatResult combatResultado = napakalakiModel.developCombat();
        combatResult.setVisible(true);
        //Las etiquetas HTML, a parte de para dar color(no puedo ponerlo directamente en la etiqueta, porque si no, no es dinamico) tambien sirven para que el texto se ajuste
        //al marco que le hemos puesto, osea para que sea multilinea. Jlabel si no pones la etiqueta html, no es multilinea.
          switch (combatResultado) {
            case WinAndWinGame : 
              String msj = "<html><div style='color: green;'>¡¡¡ H A S   G A N A D O   L A   P A R T I D A !!!</div></html>";
              combatResult.setText(msj);
              JOptionPane.showMessageDialog(null, msj, "Mensaje de Error", JOptionPane.OK_OPTION);
              System.exit(0);
              break;
            case Win :
              combatResult.setText("<html><div style='color: green;'>Ganaste el combate</div></html>");
              break;
            case Lose :
              combatResult.setText("<html><div style='color: #008B8B;'>Has perdido el combate, te toca cumplir el mal rollo</div></html>");
              break;
            case LoseAndEscape :
              combatResult.setText("<html><div style='color: green;'>Perdiste el combate pero has logrado escapar</div></html>");
              break;
            case LoseAndDie :
              combatResult.setText("<html><div style='color: red;'>Perdiste el combate y además estás muerto</div></html>");
                break;
            case LoseAndConvert :
              combatResult.setText("<html><div style='color: red;'>Perdiste el combate, Y te has convertido.</div></html>");
              break;
          }
        combatButton.setEnabled(false);
        nextTurnButton.setVisible(true);
        playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
        playerView1.enableBuy(false);
        playerView1.enableMake(true);
    }//GEN-LAST:event_combatButtonActionPerformed

    private void nextTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTurnButtonActionPerformed
        
        if (!napakalakiModel.nextTurn()){
            String msj = "<html> ERROR <br> No cumples las condiciones para pasar de turno <br> O bien tienes más de 4 tesoros ocultos <br> O bien te queda mal rollo por cumplir<html>";
            JOptionPane.showMessageDialog(null, msj, "Mensaje de Error", JOptionPane.ERROR_MESSAGE); 
        }else{
            combatResult.setVisible(false);
            meetButton.setVisible(true);
            combatButton.setVisible(false);
            nextTurnButton.setVisible(false);            
            playerView1.enableMake(napakalakiModel.getCurrentPlayer().isDead());
            playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
            playerView1.enableBuy(true);
            monsterView1.setMonster(null);
            repaint();
            revalidate();
        }
        
        
    }//GEN-LAST:event_nextTurnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showView() {
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combatButton;
    private javax.swing.JLabel combatResult;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton meetButton;
    private GUI.MonsterView monsterView1;
    private javax.swing.JButton nextTurnButton;
    private GUI.PlayerView playerView1;
    // End of variables declaration//GEN-END:variables
}
