/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki.Prize;

/**
 *
 * @author Play
 */
public class PrizeView extends javax.swing.JPanel {
            
     Prize prizeModel;
    /**
     * Creates new form PrizeView
     */
    public PrizeView() {
        initComponents();
    }

    public void setPrize (Prize t) {
        prizeModel = t;
        PrizeLevel.setText(Integer.toString(prizeModel.getLevel()) + " Nivel/es");
        PrizeTreasure.setText(Integer.toString(prizeModel.getTreasures()) + " Tesoro/s");
        repaint();
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrizeTreasure = new javax.swing.JLabel();
        PrizeLevel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PrizeTreasure.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        PrizeTreasure.setText("Tesoros");
        add(PrizeTreasure, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        PrizeLevel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        PrizeLevel.setText("Niveles");
        add(PrizeLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PrizeLevel;
    private javax.swing.JLabel PrizeTreasure;
    // End of variables declaration//GEN-END:variables
}
