package GUI;

import java.awt.Color;
import napakalaki.Treasure;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Play
 */
public class TreasureView extends javax.swing.JPanel {
        Treasure treasureModel;
         boolean selected;
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }
    
    

    public void setTreasure (Treasure t) {
        treasureModel = t;
       /* Poro.setText(Integer.toString(treasureModel.getGoldCoins()));
        BonusMaximo.setText(Integer.toString(treasureModel.getMaxBonus()));
        BonusMinimo.setText(Integer.toString(treasureModel.getMinBonus()));
        TipoTreasure.setText(treasureModel.getType().toString());
        NombreTreasure.setText((treasureModel.getName()));
        */
        
        EquipIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/equipamiento/" + t.getIcon())));
        repaint();
    }

    public Treasure getTreasure() {
        return treasureModel;
    }
    
    public boolean isSelected(){
        return selected;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        EquipIcon = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(65, 65));
        setMinimumSize(new java.awt.Dimension(65, 65));
        setPreferredSize(new java.awt.Dimension(65, 65));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 12, -1, -1));

        EquipIcon.setMaximumSize(new java.awt.Dimension(65, 65));
        EquipIcon.setMinimumSize(new java.awt.Dimension(65, 65));
        add(EquipIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    
        if(selected){
            selected = false;
        }else if(!selected){
            selected = true;
        }
        
        setBackground(Color.lightGray);
        setOpaque(selected);
        repaint();
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EquipIcon;
    private javax.swing.Box.Filler filler1;
    // End of variables declaration//GEN-END:variables
}
